version: '3'

volumes:
  spring-demo:

services:
  db-demo:
    image: postgres
    ports:
      - '15432:5432'
    volumes:
      - 'spring-demo:/var/lib/postgresql/data'
      - './dbinit:/docker-entrypoint-initdb.d'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres